### ISSUE TITLE
Error in evaluate_changes_clevr.py

### ISSUE THREAD

**Issue by mohit291298** [he-dhamo/simsg#5]

**Comment by mohit291298** [comment]
Hi, The following doesn't work (I am using 
PerceptualSimilarity @ 5d2afe2 ):

import models as util

Also, I get this error:
Traceback (most recent call last):
  File "scripts/evaluate_changes_clevr.py", line 37, in <module>
    from PerceptualSimilarity import models
  File "/home/cse/dual/cs5160433/simsg/PerceptualSimilarity/models/__init__.py", line 11, in <module>
    from models import dist_model
ModuleNotFoundError: No module named 'models'

Any idea how to resolve this?
